name: stops_sg
description: A Flutter application that displays live bus timings for bus stops in Singapore

version: 0.5.1+11

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  edit_distance: ^0.4.1
  expandable: ^2.2.0
  flutter_launcher_icons: ^0.7.3
  flutter_local_notifications: ^1.4.4
  google_maps_flutter: ^0.5.28+1
  implicitly_animated_reorderable_list: ^0.2.2
  latlong: ^0.6.1
  location: ^2.3.5
  path:
  quick_actions: ^0.3.0+1
  rubber: ^0.4.0
  shared_preferences: 0.5.2
  shimmer: ^1.1.1
  sqflite: ^1.3.0
  url_launcher: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon.png"
  adaptive_icon_foreground: "assets/images/icon/icon_fg.png"
  adaptive_icon_background: "assets/images/icon/icon_bg.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: 'B612 Mono'
      fonts:
      - asset: assets/fonts/B612Mono-Regular.ttf
      - asset: assets/fonts/B612Mono-Italic.ttf
        style: italic
      - asset: assets/fonts/B612Mono-Bold.ttf
        weight: 700
      - asset: assets/fonts/B612Mono-BoldItalic.ttf
        style: italic
        weight: 700
    - family: 'Source Sans Pro'
      fonts:
      - asset: assets/fonts/SourceSansPro-Light.ttf
        weight: 300
      - asset: assets/fonts/SourceSansPro-Regular.ttf
        weight: 400

  assets:
    - assets/secrets.json
    - assets/maps/map_style_dark.json