name: stops_sg
description: A Flutter application that displays live bus timings for bus stops in Singapore

version: 0.7.0+17

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager: ^2.0.2
  cupertino_icons: ^1.0.3
  edit_distance: ^0.5.0-nullsafety.0
  expandable: ^5.0.1
  flutter_launcher_icons: ^0.9.1
  flutter_local_notifications: ^8.1.1+1
  flutter_nfc_kit: ^1.1.0
  flutter_svg: ^0.22.0
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.6
  implicitly_animated_reorderable_list: ^0.4.0
  latlong: ^0.6.1
  location: ^4.3.0
  path: ^1.8.0
  quick_actions: ^0.6.0+3
  rubber: ^1.0.1
  shared_preferences: ^2.0.6
  shimmer: ^2.0.0
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon/icon.png"
  adaptive_icon_foreground: "assets/images/icon/icon_fg.png"
  adaptive_icon_background: "assets/images/icon/icon_bg.png"

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/bus-stop.svg
    - assets/images/pin.svg
    - assets/images/pin-outline.svg
    - assets/images/icon/
    - assets/secrets.json
    - assets/maps/map_style_dark.json
